### ISSUE TITLE
allow recursive replacement for list

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/meddle#28]
right now 
```yaml
process-description: data were pulled or synthesized from existing etc...
```
will be replaced within `render` if
```r
render(global.yaml, NULL, list('process-description' = 'updated data description'))
```
but there isn't a way to deal with the nested replacement:
```yaml
attributes: 
  - 
    attr-label: DateTime
    attr-def: The date and time of day
    attr-defs: Pope Gregory XIII
    data-min: 2007-01-01 00:00:00
    data-max: 2016-03-16 00:00:00
    data-units: time
```
in code:
```r
render(global.yaml, NULL, list('attributes' = list('attributes'=c(list('attr-label'="DateTime", 'data-min'='2007-01-03 12:00:00'))))
```
will replace the whole `attributes` list
