### ISSUE TITLE
add feature_type method for polyline objects (sfc_LINESTRING)

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/meddle#70]
* Add a new `feature_type` method [here](https://github.com/USGS-R/meddle/blob/master/R/extract_spatial.R#L71) for `sfc_LINESTRING`

**Comment by jread-usgs** [comment]
Really weird that there isn't a name in here for vector lines: https://www.fgdc.gov/metadata/csdgm/03.html

@hcorson-dosch do you have an example file or rds you could share that is the type of sfc_LINSTRING we'd like to support? I want to make sure we get something adequate for the tests and to make sure the feature counts are correct (e.g., making sure we're counting line segments instead of nodes).

**Comment by hcorson-dosch** [comment]
I ran into this error when I was trying to run `extract_feature()` on `network.rds` from `delaware-model-prep` ([link](https://drive.google.com/file/d/1T9zQowC4ySUy64hvSqYWPP1ElYGgy1xl/view?usp=sharing)) so that would be good file for testing it.

As for the FGDC  Spatial Data Transfer Standard Point and Vector Object Types I'm _pretty_ sure that `string` is the term used for a standard polyline (a.k.a. linestring)

**Comment by jread-usgs** [comment]
Based on the current fix I am working on in my fork: 
```r
readRDS('~/Downloads/network.rds')$edges%>% st_transform('WGS84') %>% extract_feature()
```

```yaml
wbbox: -76.3879906
ebbox: -74.3807851
nbbox: 42.4544545
sbbox: 38.7894548
feature-ref: Vector
feature-type: String
feature-count: 459
states:
- state-name: Delaware
  state-abbr: DE
- state-name: Maryland
  state-abbr: MD
- state-name: New Jersey
  state-abbr: NJ
- state-name: New York
  state-abbr: NY
- state-name: Pennsylvania
  state-abbr: PA
```
